name: demo-ci-cd
on: 
  push:
    branches: [main]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Nodeabc
        uses: actions/setup-node@v3
        with: 
          node-version: '12.x'
      - run: yarn
      - run: yarn build
      - run: yarn test:ci
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          # Specify Browser since container image is compile with Firefox
          install: false
          start: yarn start:test
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 200
          browser: chrome
          headless: true
          record: true