name: demo-ci-cd
on: 
  push:
    branches: [main]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Nodeabc
        uses: actions/setup-node@v3
        with: 
          node-version: '12.x'
      - run: yarn
      - run: npm build
      - run: yarn test:ci
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          # Specify Browser since container image is compile with Firefox
          build: npm i -D cypress
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Login with docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN}}
      - name: setup docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: build and push Docker image
        uses: docker/build-push-action@v1
        id: docker-build
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.builx.output.name}}
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/docker-deploy-full-crown 
      - name: verify
        run: echo done ${{steps.docker-build.output.digest}}, Happy to code