name: demo-ci-cd
on: 
  push:
    branches: [main]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Nodeabc
        uses: actions/setup-node@v3
        with: 
          node-version: '12.x'
      - run: yarn
      - run: yarn build
      - run: yarn test